
import Sidebar from "../Components/UserShared/Sidebar/Sidebar";
import "../globals.css";


export const metadata = {
  title: "My Portfolio",
  description: "Generated by Tamzid ",
};

const HomeLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className="flex"
      >
        <div><Sidebar /></div>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}


export default HomeLayout;
