
import "../globals.css";


export const metadata = {
  title: "My Portfolio",
  description: "Generated by Tamzid ",
};

const HomeLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}


export default HomeLayout;
