
import Sidebar from "../Components/UserShared/Sidebar/Sidebar";
import "../globals.css";


export const metadata = {
  title: "My Portfolio",
  description: "Generated by Tamzid ",
};

const HomeLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className="flex"
      >
        <div className="fixed top-0 left-0 h-screen"><Sidebar /></div>
        <div className="ml-[550px] w-full h-screen overflow-y-scroll scroll-smooth">
          {children}
        </div>
      </body>
    </html>
  );
}


export default HomeLayout;
