import React from 'react';
import ClientWrapper from './ClientWrapper/ClientWrapper';

export const metadata = {
    title: "Tamzid || Front End Developer",
    description: "Generated by Tamzid ",
  };

const RootLayout = ( {children}) => {
    return (
        <html lang="en">
        <body>
          <ClientWrapper>
            {children}
          </ClientWrapper>
        </body>
    </html>
    );
};

export default RootLayout;